name: Gitee repos mirror job

on:
  push:
    branches:
      - master
      - develop

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: github/terwer
          dst: gitee/youweics
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          account_type: user
          timeout: 600
          debug: true
          force_update: true
          white_list: 'html-to-docx'
